#----------------------------------------------------------------------
# This file was generated by C:/Users/qingyang.a.zhao/PycharmProjects/jfeUI/EncodeBitmapsUtil.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

back = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAALRJREFU'
    b'OE+l0zEOAVEUheHPKkSlYA9qjVoQGmoLEIVOqdPYgS0oVLQ2oFTTaig0MsmMyIR5w7zu5d7z'
    b'59z7zispeEoF9bIATezI7PlaHGGBIfZZLj85mKGLAU6hEdOAJWox4BESR/V3wBo3jPMIk54E'
    b'sMXhF2HcO08AG9xx/BHyAkS6FaroINf86R1E9yla6OGax82nZ+xjgjbOIci3JDbipdZDWciK'
    b'chmXf6OcOK+Exij8G5/QlRgRa0K0yAAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
logo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACUAAAAgCAYAAACVU7GwAAAAAXNSR0IArs4c6QAABENJREFU'
    b'WEfVl11oHFUUx//nTlPMQ5tkhlbUogXBRopWqYWCyWyCFqkPitgNyaZg9KHaIlREQRRJDVQF'
    b'RaTgF/UjD9lZJS3oi4JYkuzGPhQ/QNFalGjxg0rNThsUbTZz/3Jnd5LNdNOMNUv0Pix34cyZ'
    b'3/zP/8y5I0i4MoUzm/VMaVU83GpUn2W3OlMJ0yQKkyRR3SP+emXx+1qxBEZzrt2ZJE/SmIRQ'
    b'pzuUZY0slNRz7UR56gYVAXSPzIH+76F2jk9t4IrSH9mtzk8LKZdI9lqqJFGqZ3Rym4DXQqlW'
    b'ATYRvBGQRgNDYFPOtb+oBRZC9Y34zdOW/giQzfEgHQShiWc9RT4VxgiuAqTPbGuVL5P/rQ9Q'
    b'by2shtqVdZsPLghV/dSLQZluE6AD4OCFoHrGiveL4NXyA8gb1Po4yQmlrF6Ad4M84KWcvcmg'
    b'IiUq0Vrr0WqlkkL1fnx2C4PgWMi0kk3Ru6y3UHyGxGMAj3iuc2siqFqlqFYyKVT6K65smPTP'
    b'hVDkbdmU86HZ9xT8e4V8k+CpnOtclhiqJ1+cfScxCEIPRZ5KCmWuyeSLxsjXEezPuc5AGarY'
    b'JkQhzKlWtA61rT4RBwuNHu+kTL7IKJCQDgYzcjFQvXl/kOA9ID7wUvbtc03FHwA0CZjOus6h'
    b'ZFAFv38Wihi9WKjMmL8XwhcB+J5r21HOTN4/BnALhPu8dqfczVUrVKon76cEDA1tPHUxSpmS'
    b'l7uy9lIM7gyUtQ5EWgS/gMgAMuy5LV3LBiXA4wSeBjEpCgfLHYivPdfemAjKKFcdmKR8xpfn'
    b'Jbes/ln1lHoUWj8XdqOo/aR+wuxL59A8vM0+u+TlQ0nWo4G5WGJqYLqqpK8A2F2GwrMVpaA0'
    b'3KEOO+zGaC3qqfPGjMg+aC3VY6YCZTqqOvHRGNTnEDSCaAVkEILtIC8VwYPZdvulRaHiZVhs'
    b'IM+DIr+BiBnAcSij0eFwxICfAvIngDYRvJZttx+oL5RwHJS22lCISjgtIkMk74Ng3Gu325cB'
    b'ilOArIbICyAfrgAYo+8HccZL2S11hpJPQN40XymeAGQDKAcg3AXgEhE+QsrzIQxnrvFSa7+9'
    b'oNH/lacqF8fKlwfgAngXkCsgOA7qk4A8GTKBO3Kuc7gOUAiPKXOJ+V3UfQQPCWQHyVMzvx5Z'
    b'N9zVFZi4TL54EsCVBAdyrjM72mq+Ev6pUgt9OESjh8TLItgTvqOI67Mp+8sQqlB8H8R2o6Dn'
    b'2nctqVKLQcEcHEXtAbhGyO5synmnrNTkQKWEE55rX70MUGgD5JbqUu0c8+/QwvcMTCmYWTXc'
    b'ufb3UE3zEz8lLHX5jFIiqongQ8ZfOddJm3t0j5++XGnrZ7NX5M1DKefoPKgIJOe2jNUDCpb1'
    b'I7R+PToZZAqTaVClAYaAAuzOunb4oTHv7BSHWY7/xp//Taha56B6KSSWukFB/wU2TAS6NF3r'
    b'Pm93rhn9G75bAE5MckpHAAAAAElFTkSuQmCC')

